// Package main contains an example of how to use totp.TOTP.
package main

import (
	"fmt"
	"time"

	"github.com/alnvdl/totp/totp"
)

// main contains an example of how to use totp.TOTP.
func main() {
	// The key must be kept secret, and preferrably encrypted-at-rest.
	key := []byte("abcde")
	// You can add this key manually to a TOTP authenticator app. To do that,
	// you need to base32-encode it first:
	//     $ echo -n "abcde" | base32
	//     MFRGGZDF

	// The code generated by this should match the one in the TOTP
	// authenticator app.
	fmt.Println(totp.TOTP(key, time.Now()))
}
